services:
  unleash:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_PATH: /usr/src/unleash
    container_name: unleash
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - ENVIRONMENT=development
      - PORT=3000
      - DATA_SOURCE=addresses.json

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
